# Generated by Django 5.0.6 on 2026-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=40)),
                ('confidence', models.FloatField(default=0)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='objects/')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_detections', to='cameras.camera')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_detections', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'تشخیص شیء',
                'verbose_name_plural': 'تشخیص\u200cهای شیء',
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='PlateRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=32)),
                ('confidence', models.FloatField(default=0)),
                ('country', models.CharField(blank=True, default='ir', max_length=8)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='plates/')),
                ('watchlist_hit', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_reads', to='cameras.camera')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_reads', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'خواندن پلاک',
                'verbose_name_plural': 'خواندن\u200cهای پلاک',
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('motion', 'حرکت'), ('object', 'تشخیص شیء'), ('alpr', 'پلاک خودرو')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('interval_seconds', models.PositiveIntegerField(default=15)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_rules', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_rules', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'قانون تحلیل',
                'verbose_name_plural': 'قوانین تحلیل',
                'unique_together': {('camera', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='PlateWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_watchlist', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'plate')},
            },
        ),
    ]
