# Generated by Django 5.0.6 on 2026-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_threat_level'),
        ('analytics', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsrule',
            name='kind',
            field=models.CharField(choices=[('motion', 'حرکت'), ('object', 'تشخیص شیء'), ('alpr', 'پلاک خودرو'), ('fire', 'آتش'), ('smoke', 'دود'), ('tripwire', 'عبور از خط')], max_length=10),
        ),
        migrations.CreateModel(
            name='MotionHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('grid', models.JSONField(blank=True, default=list)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'نقشه حرارتی حرکت',
                'verbose_name_plural': 'نقشه\u200cهای حرارتی حرکت',
                'unique_together': {('camera', 'date')},
            },
        ),
    ]
