# Generated by Django 5.0.6 on 2026-08-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsrule_kind_motionheatmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('task', models.CharField(choices=[('object', 'تشخیص شیء'), ('alpr', 'پلاک خودرو'), ('fire', 'آتش'), ('smoke', 'دود'), ('face', 'چهره')], db_index=True, max_length=8)),
                ('version', models.CharField(default='v1', max_length=40)),
                ('framework', models.CharField(choices=[('onnx', 'ONNX Runtime'), ('opencv', 'OpenCV DNN'), ('dummy', 'آزمایشی/شبیه\u200cسازی')], default='onnx', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('input_w', models.PositiveIntegerField(default=640)),
                ('input_h', models.PositiveIntegerField(default=640)),
                ('classes', models.JSONField(blank=True, default=list)),
                ('min_confidence', models.FloatField(default=0.35)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('device', models.CharField(choices=[('cpu', 'CPU'), ('cuda', 'CUDA / GPU')], default='cpu', max_length=4)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدل تشخیص',
                'verbose_name_plural': 'مدل\u200cهای تشخیص',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['task', 'active'], name='analytics_d_task_2259bb_idx')],
            },
        ),
    ]
