# Generated by Django 5.0.6 on 2026-07-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_threat_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام چیدمان')),
                ('tile_count', models.PositiveSmallIntegerField(default=4)),
                ('tiles', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_layouts', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'چیدمان میز هوشمند',
                'verbose_name_plural': 'چیدمان\u200cهای میز هوشمند',
                'ordering': ('name',),
                'unique_together': {('user', 'name')},
            },
        ),
    ]
