# Generated by Django 5.0.6 on 2026-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام سرور')),
                ('base_url', models.CharField(max_length=300, verbose_name='آدرس پایه')),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('online', 'آنلاین'), ('offline', 'آفلاین'), ('unknown', 'نامشخص')], default='unknown', max_length=8)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('camera_count', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federated_servers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'سرور فدراسیون',
                'verbose_name_plural': 'سرورهای فدراسیون',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RemoteCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='unknown', max_length=10)),
                ('webrtc_url', models.CharField(blank=True, default='', max_length=400)),
                ('hls_url', models.CharField(blank=True, default='', max_length=400)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_cameras', to='federation.federatedserver')),
            ],
            options={
                'unique_together': {('server', 'remote_id')},
            },
        ),
    ]
