# Generated by Django 5.0.6 on 2026-07-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='cameras.camera')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('motion', 'حرکت'), ('alpr', 'پلاک خودرو'), ('object', 'تشخیص شیء'), ('offline', 'قطع ارتباط'), ('tamper', 'دستکاری'), ('manual', 'دستی')], max_length=12)),
                ('severity', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='info', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acked_events', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ('-ts',),
                'indexes': [models.Index(fields=['organization', '-ts'], name='events_even_organiz_54a463_idx')],
            },
        ),
    ]
