# Generated by Django 5.0.6 on 2026-07-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_threat_level'),
        ('cameras', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام قانون')),
                ('enabled', models.BooleanField(default=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=12)),
                ('min_severity', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='info', max_length=10)),
                ('action', models.CharField(choices=[('webhook', 'فراخوانی وب\u200cهوک'), ('unlock_door', 'بازکردن در'), ('lock_door', 'قفل\u200cکردن در'), ('set_threat', 'تغییر سطح تهدید')], max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'قانون خودکارسازی',
                'verbose_name_plural': 'قوانین خودکارسازی',
                'ordering': ('name',),
            },
        ),
    ]
