# Generated by Django 5.0.6 on 2026-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_automationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='action',
            field=models.CharField(choices=[('webhook', 'فراخوانی وب\u200cهوک'), ('unlock_door', 'بازکردن در'), ('lock_door', 'قفل\u200cکردن در'), ('set_threat', 'تغییر سطح تهدید'), ('send_sms', 'ارسال پیامک'), ('voice_call', 'تماس صوتی')], max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('motion', 'حرکت'), ('alpr', 'پلاک خودرو'), ('object', 'تشخیص شیء'), ('fire', 'آتش'), ('smoke', 'دود'), ('tripwire', 'عبور از خط'), ('offline', 'قطع ارتباط'), ('tamper', 'دستکاری'), ('manual', 'دستی')], max_length=12),
        ),
    ]
