# Generated by Django 5.0.6 on 2026-07-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_threat_level'),
        ('events', '0003_alter_automationrule_action_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('console', 'فقط ثبت در لاگ (بدون حساب)'), ('kavenegar', 'کاوه\u200cنگار (ایران)'), ('twilio', 'Twilio (بین\u200cالمللی)')], default='console', max_length=20)),
                ('kavenegar_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('sms_sender', models.CharField(blank=True, default='', max_length=40)),
                ('twilio_sid', models.CharField(blank=True, default='', max_length=100)),
                ('twilio_token', models.CharField(blank=True, default='', max_length=100)),
                ('twilio_from', models.CharField(blank=True, default='', max_length=40)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلان\u200cها',
            },
        ),
    ]
