# Generated by Django 5.0.6 on 2026-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('motion', 'حرکت'), ('alpr', 'پلاک خودرو'), ('object', 'تشخیص شیء'), ('fire', 'آتش'), ('smoke', 'دود'), ('tripwire', 'عبور از خط'), ('offline', 'قطع ارتباط'), ('tamper', 'دستکاری'), ('manual', 'دستی'), ('storage', 'فضای ذخیره\u200cسازی')], max_length=12),
        ),
    ]
