# Generated by Django 5.0.6 on 2026-08-02 12:55

import apps.cameras.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_assigned_to_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='kavenegar_api_key',
            field=apps.cameras.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='twilio_token',
            field=apps.cameras.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
