# Generated by Django 5.0.6 on 2026-07-06 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پرونده')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته'), ('archived', 'بایگانی')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_cases', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'پروندهٔ مدارک',
                'verbose_name_plural': 'پرونده\u200cهای مدارک',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody', to='evidence.evidencecase')),
            ],
            options={
                'ordering': ('ts',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recording', 'ضبط'), ('export', 'خروجی'), ('snapshot', 'عکس'), ('note', 'یادداشت')], max_length=10)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evidence.evidencecase')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordings.recording')),
            ],
            options={
                'ordering': ('added_at',),
            },
        ),
    ]
