# Generated by Django 5.0.6 on 2026-07-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('running', 'در حال پردازش'), ('done', 'آماده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('output_file', models.CharField(blank=True, default='', max_length=500)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cameras.camera')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecordingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'خاموش'), ('continuous', 'پیوسته'), ('motion', 'مبتنی بر حرکت'), ('scheduled', 'زمان\u200cبندی\u200cشده')], default='off', max_length=12)),
                ('weekly', models.JSONField(blank=True, default=dict)),
                ('retention_days', models.PositiveIntegerField(default=14, verbose_name='نگهداری (روز)')),
                ('segment_seconds', models.PositiveIntegerField(default=60)),
                ('pre_event_seconds', models.PositiveIntegerField(default=5)),
                ('post_event_seconds', models.PositiveIntegerField(default=10)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی ضبط',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای ضبط',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'در حال ضبط'), (1, 'کامل'), (3, 'بایگانی')], default=1)),
                ('has_motion', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'ضبط',
                'verbose_name_plural': 'ضبط\u200cها',
                'ordering': ('-start',),
                'indexes': [models.Index(fields=['camera', 'start'], name='recordings__camera__0a14f1_idx')],
            },
        ),
    ]
