# Generated by Django 5.0.6 on 2026-08-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_encrypt_camera_password'),
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordingschedule',
            options={'ordering': ('camera_id',), 'verbose_name': 'زمان\u200cبندی ضبط', 'verbose_name_plural': 'زمان\u200cبندی\u200cهای ضبط'},
        ),
        migrations.CreateModel(
            name='ManualRecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recording', 'در حال ضبط'), ('stopped', 'متوقف\u200cشده')], db_index=True, default='recording', max_length=12)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_sessions', to='cameras.camera')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ضبط دستی',
                'verbose_name_plural': 'ضبط\u200cهای دستی',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['camera', 'status'], name='recordings__camera__0410c4_idx')],
            },
        ),
    ]
