# Generated by Django 5.0.6 on 2026-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_recordingschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
