# Generated by Django 5.0.6 on 2026-08-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_encrypt_camera_password'),
        ('events', '0005_alter_event_type'),
        ('recordings', '0003_recording_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('assembling', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=12)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('protected_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_clips', to='cameras.camera')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clip', to='events.event')),
            ],
            options={
                'verbose_name': 'کلیپ رویداد',
                'verbose_name_plural': 'کلیپ\u200cهای رویداد',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['camera', 'start'], name='recordings__camera__ad8418_idx')],
            },
        ),
    ]
