# Generated by Django 5.0.6 on 2026-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_eventclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
