# Generated by Django 5.0.6 on 2026-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='threat_level',
            field=models.CharField(default='green', max_length=8),
        ),
    ]
