# Generated by Django 5.0.6 on 2026-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام نقشه')),
                ('image', models.ImageField(upload_to='maps/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'نقشه',
                'verbose_name_plural': 'نقشه\u200cها',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('camera', 'دوربین'), ('door', 'در')], max_length=8)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('x', models.FloatField(default=0.5)),
                ('y', models.FloatField(default=0.5)),
                ('rotation', models.FloatField(default=0)),
                ('site_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='maps.sitemap')),
            ],
            options={
                'verbose_name': 'نشانگر نقشه',
                'verbose_name_plural': 'نشانگرهای نقشه',
            },
        ),
    ]
