# Generated by Django 5.0.6 on 2026-07-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام دوربین')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='محل نصب')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('protocol', models.CharField(default='rtsp', max_length=10)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=554)),
                ('path', models.CharField(blank=True, default='/', max_length=255)),
                ('rtsp_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس کامل RTSP')),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('onvif_host', models.CharField(blank=True, default='', max_length=255)),
                ('onvif_port', models.PositiveIntegerField(default=80)),
                ('onvif_enabled', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('online', 'آنلاین'), ('offline', 'آفلاین'), ('unknown', 'نامشخص'), ('disabled', 'غیرفعال')], default='unknown', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ptz_enabled', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'دوربین',
                'verbose_name_plural': 'دوربین\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('layout', models.CharField(default='2x2', max_length=10)),
                ('cameras', models.ManyToManyField(blank=True, related_name='groups', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_groups', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'گروه دوربین',
                'verbose_name_plural': 'گروه\u200cهای دوربین',
            },
        ),
        migrations.CreateModel(
            name='PtzPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('token', models.CharField(blank=True, default='', max_length=80)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptz_presets', to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StreamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('main', 'جریان اصلی'), ('sub', 'جریان فرعی')], default='main', max_length=8)),
                ('codec', models.CharField(default='h264', max_length=20)),
                ('resolution', models.CharField(default='1280x720', max_length=20)),
                ('fps', models.PositiveIntegerField(default=25)),
                ('bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('rtsp_transport', models.CharField(default='tcp', max_length=8)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_profiles', to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera', 'kind')},
            },
        ),
    ]
