# Generated by Django 5.0.6 on 2026-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprofile',
            name='codec',
            field=models.CharField(choices=[('h264', 'H.264 / AVC'), ('h265', 'H.265 / HEVC (و H.265+)')], default='h264', max_length=20),
        ),
    ]
