# Generated by Django 5.0.6 on 2026-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('employee_id', models.CharField(blank=True, default='', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cardholders/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardholders', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'دارندهٔ کارت',
                'verbose_name_plural': 'دارندگان کارت',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام در')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('controller_url', models.CharField(blank=True, default='', max_length=300)),
                ('relay', models.PositiveIntegerField(default=1)),
                ('unlock_seconds', models.PositiveIntegerField(default=5)),
                ('state', models.CharField(choices=[('locked', 'قفل'), ('unlocked', 'باز'), ('held', 'نگه\u200cداشته باز'), ('offline', 'آفلاین')], default='locked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'در',
                'verbose_name_plural': 'درها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_value', models.CharField(blank=True, default='', max_length=64)),
                ('decision', models.CharField(choices=[('granted', 'مجاز'), ('denied', 'غیرمجاز')], max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='accounts.organization')),
                ('cardholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.cardholder')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='access.door')),
            ],
            options={
                'verbose_name': 'رویداد تردد',
                'verbose_name_plural': 'رویدادهای تردد',
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('card', 'کارت'), ('pin', 'رمز'), ('plate', 'پلاک خودرو')], default='card', max_length=8)),
                ('value', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='access.cardholder')),
            ],
            options={
                'unique_together': {('kind', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('weekly', models.JSONField(blank=True, default=dict)),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access.cardholder')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access.door')),
            ],
            options={
                'unique_together': {('door', 'cardholder')},
            },
        ),
    ]
