# Generated by Django 5.0.6 on 2026-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholder',
            name='host',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='میزبان'),
        ),
        migrations.AddField(
            model_name='cardholder',
            name='kind',
            field=models.CharField(choices=[('employee', 'کارمند'), ('visitor', 'مهمان'), ('contractor', 'پیمانکار')], default='employee', max_length=12),
        ),
        migrations.AddField(
            model_name='cardholder',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardholder',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
